TRUNCATE TABLE board;
TRUNCATE TABLE board_comment;
TRUNCATE TABLE board_recommend;
TRUNCATE TABLE crud;
TRUNCATE TABLE members;

ALTER TABLE board AUTO_INCREMENT = 1;
ALTER TABLE board_comment AUTO_INCREMENT = 1;
ALTER TABLE board_recommend AUTO_INCREMENT = 1;
ALTER TABLE crud AUTO_INCREMENT = 1;
ALTER TABLE members AUTO_INCREMENT = 1;
