<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>
<script src="/admin_assets/js/jquery-1.9.1.min.js"></script>
<script src="/admin_assets/js/jquery-migrate-1.0.0.min.js"></script>
<script src="/admin_assets/js/jquery-ui-1.10.0.custom.min.js"></script>
<script src="/admin_assets/js/jquery.ui.touch-punch.js"></script>
<script src="/admin_assets/js/modernizr.js"></script>
<script src="/admin_assets/js/bootstrap.min.js"></script>
<script src="/admin_assets/js/jquery.cookie.js"></script>
<script src="/admin_assets/js/fullcalendar.min.js"></script>
<script src="/admin_assets/js/jquery.dataTables.min.js"></script>
<script src="/admin_assets/js/excanvas.js"></script>
<script src="/admin_assets/js/jquery.flot.js"></script>
<script src="/admin_assets/js/jquery.flot.pie.js"></script>
<script src="/admin_assets/js/jquery.flot.stack.js"></script>
<script src="/admin_assets/js/jquery.flot.resize.min.js"></script>
<script src="/admin_assets/js/jquery.chosen.min.js"></script>
<script src="/admin_assets/js/jquery.uniform.min.js"></script>
<script src="/admin_assets/js/jquery.cleditor.min.js"></script>
<script src="/admin_assets/js/jquery.noty.js"></script>
<script src="/admin_assets/js/jquery.elfinder.min.js"></script>
<script src="/admin_assets/js/jquery.raty.min.js"></script>
<script src="/admin_assets/js/jquery.iphone.toggle.js"></script>
<script src="/admin_assets/js/jquery.uploadify-3.1.min.js"></script>
<script src="/admin_assets/js/jquery.gritter.min.js"></script>
<script src="/admin_assets/js/jquery.imagesloaded.js"></script>
<script src="/admin_assets/js/jquery.masonry.min.js"></script>
<script src="/admin_assets/js/jquery.knob.modified.js"></script>
<script src="/admin_assets/js/jquery.sparkline.min.js"></script>
<script src="/admin_assets/js/counter.js"></script>
<script src="/admin_assets/js/retina.js"></script>
<script src="/admin_assets/js/custom.js"></script><?php /*modified this js*/ ?>
<script src="/admin_assets/js/bootstrap-timepicker.modified.js"></script><?php /*modified this js*/ ?>
<script src="/admin_assets/js/cleditor.js"></script>
<script src="/js/lib.global.js"></script>
<script src="/js/lib.control.js"></script>
<script src="/admin_assets/js/admin.js"></script>